name: Build & Publish to GitHub Pages (docs)

on:
  push:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm install
      - name: Build bundle
        run: npm run build
      - name: Prepare /docs
        run: |
          mkdir -p docs
          cp index.bundle.html docs/index.html
          cp test.html docs/test.html
          cp app.bundle.js docs/app.bundle.js
          touch docs/.nojekyll
      - name: Commit /docs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: build bundle and publish to docs"
          file_pattern: docs/*
